### ISSUE TITLE
Error when calling $this->socialite->with('linkedin')->user()

### ISSUE THREAD

**Issue by abishekrsrikaanth** [SocialiteProviders/LinkedIn#4]
When calling this method, I get the following error when calling 
`$this->socialite->with('linkedin')->user()`

**Error Message:** "Client error: 400"
**Stack Trace:**
```
#0 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
  #1 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(165): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
  #2 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Object(GuzzleHttp\Psr7\Response))
  #3 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
  #4 /var/www/html/ceevee/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
  #5 /var/www/html/ceevee/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
  #6 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
  #7 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
  #8 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
  #9 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
  #10 /var/www/html/ceevee/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
  #11 /var/www/html/ceevee/vendor/guzzlehttp/guzzle/src/Client.php(130): GuzzleHttp\Promise\Promise->wait()
  #12 /var/www/html/ceevee/vendor/guzzlehttp/guzzle/src/Client.php(88): GuzzleHttp\Client->request('post', 'https://www.lin...', Array)
  #13 /var/www/html/ceevee/vendor/socialiteproviders/linkedin/src/Provider.php(70): GuzzleHttp\Client->__call('post', Array)
  #14 /var/www/html/ceevee/vendor/socialiteproviders/linkedin/src/Provider.php(70): GuzzleHttp\Client->post('https://www.lin...', Array)
  #15 /var/www/html/ceevee/vendor/laravel/socialite/src/Two/AbstractProvider.php(180): SocialiteProviders\LinkedIn\Provider->getAccessToken('access_token_from_linked_in_removed_for_security_purpose')
  #16 /var/www/html/ceevee/app/Gateway/AuthenticateUser.php(47): Laravel\Socialite\Two\AbstractProvider->user()
  #17 /var/www/html/ceevee/app/Gateway/AuthenticateUser.php(31): CeeVee\Gateway\AuthenticateUser->getSocialUser('linkedin')
  #18 /var/www/html/ceevee/app/Http/Controllers/Auth/AuthController.php(42): CeeVee\Gateway\AuthenticateUser->execute(Array, Object(CeeVee\Http\Controllers\Auth\AuthController), 'linkedin')
  #19 [internal function]: CeeVee\Http\Controllers\Auth\AuthController->login(Object(CeeVee\Gateway\AuthenticateUser), Object(Illuminate\Http\Request), 'linkedin')
  #20 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(255): call_user_func_array(Array, Array)
  #21 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(163): Illuminate\Routing\Controller->callAction('login', Array)
  #22 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(111): Illuminate\Routing\ControllerDispatcher->call(Object(CeeVee\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'login')
  #23 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
  #24 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #25 /var/www/html/ceevee/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #26 [internal function]: CeeVee\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
  #27 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #29 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #30 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(113): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #31 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CeeVee\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'login')
  #32 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CeeVee\\Http\\Con...', 'login')
  #33 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
  #34 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
  #35 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
  #36 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #38 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #39 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #40 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
  #41 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
  #42 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(229): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
  #43 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
  #44 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #45 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #46 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
  #47 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #48 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #49 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #50 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #51 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #52 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #53 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #54 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #55 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
  #56 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #57 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #58 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
  #59 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #60 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #61 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
  #62 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
  #63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #64 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
  #65 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #66 /var/www/html/ceevee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(86): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
  #67 /var/www/html/ceevee/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
  #68 {main}"""
```
**Reason Phrase from Guzzle Response:** Bad Request
**HTTP Code from Suzzle Response:** 400 

Could you please let me know what is wrong

**Comment by DraperStudio** [comment]
Could you please check which socialiteprovider/manager version is installed.

**Comment by abishekrsrikaanth** [comment]
`"socialiteproviders/manager": "^0.1.10",`

Thats the version I am on and I am using Laravel 5.1

**Comment by DraperStudio** [comment]
Alright, could you do `composer show guzzlehttp/guzzle` to see which guzzle version is installed?

I will test the provider tomorrow with Laravel 5.1 myself if I can find time for it.

**Comment by abishekrsrikaanth** [comment]
```
$ composer show guzzlehttp/guzzle
name     : guzzlehttp/guzzle
descrip. : Guzzle is a PHP HTTP client library
keywords : client, curl, framework, http, http client, rest, web service
versions : dev-master, 6.0.x-dev, * 6.0.1, 6.0.0, 5.3.x-dev, 5.3.0, 5.2.0, 5.1.0, 5.0.3, 5.0.2, 5.0.1, 5.0.0, 4.2.3, 4.2.2, 4.2.1, 4.2.0, 4.1.8, 4.1.7, 4.1.6, 4.1.5, 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0, 4.0.0-rc.2, 4.0.0-rc.1, v3.8.1, v3.8.0, v3.7.4, v3.7.3, v3.7.2, v3.7.1, v3.7.0, v3.6.0, v3.5.0, v3.4.3, v3.4.2, v3.4.1, v3.4.0, v3.3.1, v3.3.0, v3.2.0, v3.1.2, v3.1.1, v3.1.0, v3.0.7, v3.0.6, v3.0.5, v3.0.4, v3.0.3, v3.0.2, v3.0.1, v3.0.0, v2.8.8, v2.8.7, v2.8.6, v2.8.5, v2.8.4, v2.8.3, v2.8.2, v2.8.1, v2.8.0, v2.7.2, v2.7.1, v2.7.0, v2.6.6, v2.6.5, v2.6.4, v2.6.3, v2.6.2, v2.6.1, v2.6.0, v2.5.0, v2.4.1, v2.4.0, v2.3.2, v2.2.4, v2.2.3, v2.2.2, v2.2.1, v2.2.0, v2.1.4, v2.1.3, v2.1.2, v2.1.1, v2.1.0, v2.0.5, v2.0.4, v2.0.3, v2.0.2, v2.0.1, v2.0.0, v1.0.4, v1.0.3
type     : library
license  : MIT License (MIT) (OSI approved) http://spdx.org/licenses/MIT#licenseText
source   : [git] https://github.com/guzzle/guzzle.git f992b7b487a816c957d317442bed4966409873e0
dist     : [zip] https://api.github.com/repos/guzzle/guzzle/zipball/f992b7b487a816c957d317442bed4966409873e0 f992b7b487a816c957d317442bed4966409873e0
names    : guzzlehttp/guzzle

autoload
files
psr-4
GuzzleHttp\ => src/

requires
guzzlehttp/promises ^1.0.0
guzzlehttp/psr7 ^1.0.0
php >=5.5.0

requires (dev)
ext-curl *
phpunit/phpunit ^4.0
psr/log ^1.0

```

**Comment by DraperStudio** [comment]
I will take a closer look tomorrow like I said but it seems like an issue with Guzzle 6 since some of the API changed.

**Comment by abishekrsrikaanth** [comment]
OK, will look forward to it. Appreciate if you can look into it at the earliest.

**Comment by DraperStudio** [comment]
Would you be able to create a test application for me since I don't have a LinkedIn account?

**Comment by DraperStudio** [comment]
Half the issue was with Guzzle 6 and the other half seems to be that I can only retrieve the name, email, etc. from separate urls and not from the people url.

So I would need to send requests to these urls because I get a 404 for the current url https://api.linkedin.com/v1/people/~:(id,formatted-name,picture-url,email-address).

https://api.linkedin.com/v1/people/~/id
https://api.linkedin.com/v1/people/~/formatted-name
https://api.linkedin.com/v1/people/~/picture-url
https://api.linkedin.com/v1/people/~/email-address

Maybe have more informations tomorrow.

**Comment by abishekrsrikaanth** [comment]
I tried this URL 

https://api.linkedin.com/v1/people/~:(id,formatted-name,picture-url,email-address)?format=json

through POSTMAN and it seemed to work fine, its probably something to do with the Guzzle changes.

You can try to test the same at https://apigee.com/console/linkedin as well

**Comment by DraperStudio** [comment]
I think the issue is that Guzzle encodes the url and LinkedIn doesn't recognize the url this way.

This is what the url looks like when Guzzle has it.
```
    -path: "/v1/people/~:%28id,formatted-name,picture-url,email-address%29"
```

Haven't found a way to disable url encoding for the request/base_url, will later try to find a solution for that.

**Comment by DraperStudio** [comment]
I did a bit more testing with the developer console on https://apigee.com/console/linkedin.

This url works fine
```
https://api.linkedin.com/v1/people/~:(id,formatted-name,picture-url,email-address)?format=json
```

This one, from Guzzle, doesn't work.
```
https://api.linkedin.com/v1/people/~:%28id,formatted-name,picture-url,email-address%29?format=json
```

It results in a 404, so it seems like my guess was right that it is an issue with the encoding of the url and LinkedIn not recognizing it.

If I can find a way to disable url/path encoding in Guzzle 6 I could verify that this is the issue.

**Comment by abishekrsrikaanth** [comment]
Any luck with this?

**Comment by DraperStudio** [comment]
No, I am waiting for a response on the issue I opened over at the Guzzle repository.

If you find a way to disable path encoding in Guzzle 6 this code should most likely work.

https://gist.github.com/DraperStudio/98ab819dd0a2dbee63b9

**Comment by DraperStudio** [comment]
Alright, https://github.com/guzzle/psr7/commit/962735c754f2a562a619b456a3aa4e614f0e5360 fixes the encoding and issue and now the following code works.

You should replace the Provider with the following contents https://gist.github.com/DraperStudio/f48b26b4bcbbb34103f5

After you have done that you should add the following to your `composer.json` and do a `sudo composer update`

```
"guzzlehttp/psr7": "dev-master"
```

I won't push this change to this repository yet because Andy and I are currently thinking about how we handle support for Guzzle 5 and 6 at the same time.

**Comment by abishekrsrikaanth** [comment]
@DraperStudio , @AndyWendt Since Socialite is setup to use either Guzzle 5 or Guzzle 6 https://github.com/laravel/socialite/blob/2.0/composer.json#L17 , would that help?

**Comment by DraperStudio** [comment]
We are most likely going to drop Guzzle 5 and PHP 5.4 completely. I am currently updating all Providers and testing changes.

In the mean time just apply the patch yourself.

**Comment by barryvdh** [comment]
I also ran across both issues.
About support 5+6, the Google Socialite provider does something like:
`$postKey = (version_compare(\GuzzleHttp\ClientInterface::VERSION, '6') === 1) ? 'form_params' : 'body';`

Also see my PR for LinkedIn in socialite: https://github.com/laravel/socialite/pull/77

**Comment by DraperStudio** [comment]
You can now pull in anything after Version 1.1.1 of our LinkedIn Provider and the issue should be gone because I require the Guzzle-PSR7 dev-master and the Guzzle 6 API changes have been applied.

**Comment by barryvdh** [comment]
Don't think that is going to work when other packages do require 6. But it's probably tagged soon anyway.

**Comment by davidnknight** [comment]
Just installed and also getting this issue?

**Comment by barryvdh** [comment]
LinkedIn is built in Socialite right now, so you dont need this.
